replicaCount: 2
image:
  repository: 437287029768.dkr.ecr.us-east-1.amazonaws.com/gitops-platform/order-service
  tag: "da52c4fa"
ingress:
  enabled: true
  className: nginx
  host: orders.local
serviceMonitor:
  enabled: false
  labels:
    release: kube-prometheus-stack
