replicaCount: 2
image:
  repository: 437287029768.dkr.ecr.us-east-1.amazonaws.com/gitops-platform/order-service
  tag: "805a78f7"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
ingress:
  enabled: true
  className: nginx
  host: orders.local
serviceMonitor:
  enabled: true
  labels:
    release: monitoring
